# Generated by Django 4.2.4 on 2023-10-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
